$(document).ready(function(){
console.log('JQuery working');
var ldept=$('#ldept').val();
var lclass=$('#lclass').val();
var ltype=$('#ltype').val();
var lsem=$('#lsem').val();
console.log(ldept+'\n'+lclass+'\n'+ltype+'\n'+lsem);

 if(lsem=="odd" && ltype=="Theory" && ldept=="IT" && lclass=="SE"){
	 	$.ajax('lc/cotitse.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/it.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}



	// $('.lvar').on('change','#ldept',function(){
	// ldept=$('#ldept').val();
	//  console.log(ldept);
	// });
	// $('.lvar').on('change','#lclass',function(){
	// lclass=$('#lclass').val();
	//  console.log(lclass);
	// });
	// $('.lvar').on('change','#ltype',function(){
 	// ltype=$('#ltype').val();
	//  console.log(ltype);
	// });
	$('.lvar').on('change',function(){
		ldept=$('#ldept').val();
		lclass=$('#lclass').val();
		ltype=$('#ltype').val();
		lsem=$('#lsem').val();
		
	console.log(ldept+'\n'+lclass+'\n'+ltype+'\n'+lsem);
	//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	if(lsem=="odd" && ltype=="Theory" && ldept=="IT" && lclass=="SE"){
	 	$.ajax('lc/cotitse.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/it.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Theory" && ldept=="IT" && lclass=="TE"){
	 	$.ajax('lc/cotitte.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/it.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Theory" && ldept=="IT" && lclass=="BE"){
	 	$.ajax('lc/cotitbe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/it.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="odd" && ltype=="Theory" && ldept=="CE" && lclass=="SE"){
	 	$.ajax('lc/cotcese.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ce.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Theory" && ldept=="CE" && lclass=="TE"){
	 	$.ajax('lc/cotcete.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ce.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Theory" && ldept=="CE" && lclass=="BE"){
	 	$.ajax('lc/cotcebe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ce.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="odd" && ltype=="Theory" && ldept=="EX" && lclass=="SE"){
	 	$.ajax('lc/cotexse.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ex.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Theory" && ldept=="EX" && lclass=="TE"){
	 	$.ajax('lc/cotexte.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ex.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Theory" && ldept=="EX" && lclass=="BE"){
	 	$.ajax('lc/cotexbe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ex.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="odd" && ltype=="Theory" && ldept=="IN" && lclass=="SE"){
	 	$.ajax('lc/cotinse.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/in.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Theory" && ldept=="IN" && lclass=="TE"){
	 	$.ajax('lc/cotinte.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/in.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Theory" && ldept=="IN" && lclass=="BE"){
	 	$.ajax('lc/cotinbe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/in.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="odd" && ltype=="Theory" && ldept=="ET" && lclass=="SE"){
	 	$.ajax('lc/cotetse.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/et.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Theory" && ldept=="ET" && lclass=="TE"){
	 	$.ajax('lc/cotette.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/et.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Theory" && ldept=="ET" && lclass=="BE"){
	 	$.ajax('lc/cotetbe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/et.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="even" && ltype=="Theory" && ldept=="IT" && lclass=="SE"){
	 	$.ajax('lc/cetitse.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/it.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Theory" && ldept=="IT" && lclass=="TE"){
	 	$.ajax('lc/cetitte.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/it.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Theory" && ldept=="IT" && lclass=="BE"){
	 	$.ajax('lc/cetitbe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/it.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="even" && ltype=="Theory" && ldept=="CE" && lclass=="SE"){
	 	$.ajax('lc/cetcese.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ce.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Theory" && ldept=="CE" && lclass=="TE"){
	 	$.ajax('lc/cetcete.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ce.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Theory" && ldept=="CE" && lclass=="BE"){
	 	$.ajax('lc/cetcebe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ce.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="even" && ltype=="Theory" && ldept=="EX" && lclass=="SE"){
	 	$.ajax('lc/cetexse.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ex.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Theory" && ldept=="EX" && lclass=="TE"){
	 	$.ajax('lc/cetexte.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ex.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Theory" && ldept=="EX" && lclass=="BE"){
	 	$.ajax('lc/cetexbe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ex.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="even" && ltype=="Theory" && ldept=="IN" && lclass=="SE"){
	 	$.ajax('lc/cetinse.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/in.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Theory" && ldept=="IN" && lclass=="TE"){
	 	$.ajax('lc/cetinte.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/in.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Theory" && ldept=="IN" && lclass=="BE"){
	 	$.ajax('lc/cetinbe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/in.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="even" && ltype=="Theory" && ldept=="ET" && lclass=="SE"){
	 	$.ajax('lc/cetetse.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/et.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Theory" && ldept=="ET" && lclass=="TE"){
	 	$.ajax('lc/cetette.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/et.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Theory" && ldept=="ET" && lclass=="BE"){
	 	$.ajax('lc/cetetbe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/et.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="odd" && ltype=="Lab" && ldept=="IT" && lclass=="SE"){
	 	$.ajax('lc/colitse.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/it.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Lab" && ldept=="IT" && lclass=="TE"){
	 	$.ajax('lc/colitte.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/it.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Lab" && ldept=="IT" && lclass=="BE"){
	 	$.ajax('lc/colitbe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/it.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="odd" && ltype=="Lab" && ldept=="CE" && lclass=="SE"){
	 	$.ajax('lc/colcese.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ce.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Lab" && ldept=="CE" && lclass=="TE"){
	 	$.ajax('lc/colcete.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ce.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Lab" && ldept=="CE" && lclass=="BE"){
	 	$.ajax('lc/colcebe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ce.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="odd" && ltype=="Lab" && ldept=="EX" && lclass=="SE"){
	 	$.ajax('lc/colexse.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ex.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Lab" && ldept=="EX" && lclass=="TE"){
	 	$.ajax('lc/colexte.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ex.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Lab" && ldept=="EX" && lclass=="BE"){
	 	$.ajax('lc/colexbe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ex.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="odd" && ltype=="Lab" && ldept=="IN" && lclass=="SE"){
	 	$.ajax('lc/colinse.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/in.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Lab" && ldept=="IN" && lclass=="TE"){
	 	$.ajax('lc/colinte.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/in.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Lab" && ldept=="IN" && lclass=="BE"){
	 	$.ajax('lc/colinbe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/in.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="odd" && ltype=="Lab" && ldept=="ET" && lclass=="SE"){
	 	$.ajax('lc/coletse.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/et.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Lab" && ldept=="ET" && lclass=="TE"){
	 	$.ajax('lc/colette.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/et.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="odd" && ltype=="Lab" && ldept=="ET" && lclass=="BE"){
	 	$.ajax('lc/coletbe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/et.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="even" && ltype=="Lab" && ldept=="IT" && lclass=="SE"){
	 	$.ajax('lc/celitse.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/it.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Lab" && ldept=="IT" && lclass=="TE"){
	 	$.ajax('lc/celitte.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/it.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Lab" && ldept=="IT" && lclass=="BE"){
	 	$.ajax('lc/celitbe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/it.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="even" && ltype=="Lab" && ldept=="CE" && lclass=="SE"){
	 	$.ajax('lc/celcese.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ce.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Lab" && ldept=="CE" && lclass=="TE"){
	 	$.ajax('lc/celcete.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ce.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Lab" && ldept=="CE" && lclass=="BE"){
	 	$.ajax('lc/celcebe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ce.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="even" && ltype=="Lab" && ldept=="EX" && lclass=="SE"){
	 	$.ajax('lc/celexse.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ex.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Lab" && ldept=="EX" && lclass=="TE"){
	 	$.ajax('lc/celexte.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ex.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Lab" && ldept=="EX" && lclass=="BE"){
	 	$.ajax('lc/celexbe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/ex.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="even" && ltype=="Lab" && ldept=="IN" && lclass=="SE"){
	 	$.ajax('lc/celinse.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/in.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Lab" && ldept=="IN" && lclass=="TE"){
	 	$.ajax('lc/celinte.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/in.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Lab" && ldept=="IN" && lclass=="BE"){
	 	$.ajax('lc/celinbe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/in.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}//wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
	else if(lsem=="even" && ltype=="Lab" && ldept=="ET" && lclass=="SE"){
	 	$.ajax('lc/celetse.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/et.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Lab" && ldept=="ET" && lclass=="TE"){
	 	$.ajax('lc/celette.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/et.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}
	else if(lsem=="even" && ltype=="Lab" && ldept=="ET" && lclass=="BE"){
	 	$.ajax('lc/celetbe.php')
			.done(function(response){
			$('#lcourse').empty();
			$('#lcourse').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
		$.ajax('lt/et.php')
			.done(function(response){
			$('#ltname').empty();
			$('#ltname').append(response);
			console.log(response)
			})
			.fail(function(request,errorType,errorMessage){
			alert(errorMessage);
			console.log(errorType);
			})
	}




	// else {
	// 	$.ajax('abc.php')

	// 	.done(function(response){
	// 		$('#lcourse').empty();
	// 		$('#lcourse').append(response);
	// 		console.log(response)
			
	// 	})
	// 	.fail(function(request,errorType,errorMessage){
	// 		alert(errorMessage);
	// 		console.log(errorType);
	// 	})

	// }
	});

});   